config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  # ログイン前のルートページを指定
  unauthenticated :user do
    root to: "static_pages#before_login", as: :unauthenticated_root
  end

  # ログイン後のルートページを指定
  authenticated :user do
    root to: "home#top", as: :authenticated_root
  end

  # user_statusのルーティング 観測地点選択のみ
  resource :user_status, only: [] do
    collection do
      # 観測地点選択用画面
      get :select_station
      # 観測地点設定処理
      patch :update_station
    end
  end

  # user_recordのルーティング
  resources :user_records, only: %i[new create update index] do
    collection do
      # 雪かき終了時の処理
      patch :finish
    end
  end

  # static_pagesのルーティング
  # プライバシーポリシー
  get "static_pages/privacy_policy"
  # 利用規約
  get "static_pages/service_of_term"
  # お問い合わせ
  get "static_pages/contact_us"
end

app/views/shared/_flash_messages.html.erb
<!-- キーとバリューを取得してフラッシュメッセージを表示 -->
<% flash.each do |key, value| %>
  <%flash_class = case key.to_s
                  when 'alert'
                    'danger'  # alertをdangerに変換
                  when 'notice'
                    'success' # noticeをsuccessに変換
                  when 'error'
                    'danger'
                  else
                    key.to_s
                  end
  %>
  <%= content_tag(:div, value, class: "alert alert-#{flash_class}", data: { turbo_cache: false }) %>
<% end %>
  
<%# Deviseなどのresourceエラーも同じ形式で表示 %>
<% if defined?(resource) && resource.errors.any? %>
  <div class="alert alert-danger" data-turbo-cache="false">
    <%= I18n.t("errors.messages.not_saved") %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-[#004681] text-[#f6f5fa] px-5 py-2">
  <div class="flex items-center justify-center bg-transparent gap-15 h-12">
    <!-- メニュー項目の表示/非表示をログイン状態に応じて切り替える -->
    <% if user_signed_in? %>
      <!-- ログイン時： -->
      <div class="opacity-50 cursor-pointer transition w-12
                  hover:opacity-100 hover:drop-shadow-[5px_5px_1px_rgba(0,0,0,0.5)]">
        <%= link_to authenticated_root_path do %>
          <%= svg_tag "icons/home" %>
        <% end %>
      </div>
      <div class="opacity-50 cursor-pointer transition w-12
                  hover:opacity-100 hover:drop-shadow-[5px_5px_1px_rgba(0,0,0,0.5)]">
        <%= link_to select_station_user_status_path do %>
          <%= svg_tag "icons/station"%>
        <% end %>
      </div>
      <div class="opacity-50 cursor-pointer transition w-12
                  hover:opacity-100 hover:drop-shadow-[5px_5px_1px_rgba(0,0,0,0.5)]">
        <%= link_to user_records_path do %>
          <%= svg_tag "icons/log"%>
        <% end %>
      </div>
      <div class="opacity-50 cursor-pointer transition w-12
                  hover:opacity-100 hover:drop-shadow-[5px_5px_1px_rgba(0,0,0,0.5)]">
        <%= link_to "#" do %>
          <%= svg_tag "icons/profile"%>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_hamburger_menu.html.erb
<!-- デフォルトでは非表示にする -->
<div>
  <nav class="hamburger-menu hidden fixed top-16 right-0 w-64 h-300 bg-[#d5e8f2] shadow-lg z-50">
    <!-- メニュー項目をログイン状態に応じて切り替える -->
      <% if user_signed_in? %>
        <!-- ログイン時： -->
        <ul class="flex items-center hamburger-content">
          <div class="text-[#004681] w-12 h-auto pl-4"><%= svg_tag "icons/information"%></div>
          <div><%= link_to "プライバシーポリシー", static_pages_privacy_policy_path %></div>
        </ul>
        <ul class="flex items-center hamburger-content">
          <div class="text-[#004681] w-12 h-auto pl-4"><%= svg_tag "icons/information"%></div>
          <div><%= link_to "利用規約", static_pages_service_of_term_path %></div>
        </ul>
        <ul class="flex items-center hamburger-content">
          <div class="text-[#004681] w-12 h-auto pl-4"><%= svg_tag "icons/mail"%></div>
          <div><%= link_to "お問い合わせ", static_pages_contact_us_path %></div>
        </ul>
        <ul class="flex items-center hamburger-content">
          <div class="text-[#004681] w-12 h-auto pl-4"><%= svg_tag "icons/logout" %></div>
          <div><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %></div>
        </ul>
      <% else %>
        <ul class="flex items-center hamburger-content">
          <div class="text-[#004681] w-12 h-auto pl-4"><%= svg_tag "icons/login" %></div>
          <div><%= link_to "ログイン", user_session_path %></div>
        </ul>
        <ul class="flex items-center hamburger-content">
          <div class="text-[#004681] w-12 h-auto pl-4"><%= svg_tag "icons/information"%></div>
          <div><%= link_to "プライバシーポリシー", static_pages_privacy_policy_path %></div>
        </ul>
        <ul class="flex items-center hamburger-content">
          <div class="text-[#004681] w-12 h-auto pl-4"><%= svg_tag "icons/information"%></div>
          <div><%= link_to "利用規約", static_pages_service_of_term_path %></div>
        </ul>
      <% end %>
  </nav>
</div>

app/views/shared/_header.html.erb
<div class="bg-[#004681] text-[#f6f5fa] px-5 py-2">
  <div class="flex items-center justify-between">
    <!-- テキストは左上に固定する -->
    <div class="flex items-center justify-center">
      <%= current_user ? "#{current_user.user_status.name} さん" : "ログインしていません" %>
    </div>
    <!-- ハンバーガーメニューボタンは右上に固定する -->
    <button class= "hamburger-button text-white opacity-50 w-12
                    transition
                    hover:opacity-100 hover:drop-shadow-[4px_4px_1px_rgba(0,0,0,1)]
                    active:opacity-100">
    <%= svg_tag "icons/hamburger"%>
    </button>
  </div>
</div>