config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  # ログイン前のルートページを指定
  unauthenticated :user do
    root to: "static_pages#before_login", as: :unauthenticated_root
  end

  # ログイン後のルートページを指定
  authenticated :user do
    root to: "home#top", as: :authenticated_root
  end

  # user_statusのルーティング 観測地点選択のみ
  resource :user_status, only: [] do
    collection do
      # 観測地点選択用画面
      get :select_station
      # 観測地点設定処理
      patch :update_station
    end
  end

  # user_recordのルーティング
  resources :user_records, only: %i[new create update index] do
    collection do
      # 雪かき終了時の処理
      patch :finish
    end
  end

  # static_pagesのルーティング
  # プライバシーポリシー
  get "static_pages/privacy_policy"
  # 利用規約
  get "static_pages/service_of_term"
  # お問い合わせ
  get "static_pages/contact_us"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # ログイン後のみ
  before_action :authenticate_user!

  def top
    # user_status.station_numberを元に観測地点の情報を表示する
    @station_number = current_user.user_status.station_number
    @station_info = SnowStation.find_by(station_number: @station_number)

    # 気温と積雪の両方が有効な最新のレコードを取得
    @latest_record = AmedasRecord.where(station_number: @station_number)
                                  .where.not(temp: nil)
                                  .where.not(snow: nil)
                                  .order(created_at: :desc)
                                  .first
    # もし両方が有効なレコードがなければ、最新のレコードを取得(ビュー側で欠測表示を行う)
    @latest_record ||= AmedasRecord.where(station_number: @station_number)
                                    .order(created_at: :desc)
                                    .first

    # 過去24時間のレコードから最高・最低気温を取得
    time_24h_ago = Time.current - 24.hours
    records_24h = AmedasRecord.where(station_number: @station_number)
                               .where("created_at >= ?", time_24h_ago)  # timeを使用
                               .where.not(temp: nil)

    @max_temp = records_24h.maximum(:temp)
    @min_temp = records_24h.minimum(:temp)
  end
end

app/views/home/top.html.erb
<% content_for(:title, t('.title')) %>

<!-- ログインユーザーの観測地点の情報を表示する -->
<div class="max-w-md pl-4 pr-10 mx-auto border rounded-md shadow-lg border-gray-500/20 backdrop-blur-lg mb-4">

  <div class="flex items-center justify-between py-6">
    <!-- 観測地点のマーク -->
    <div class="h-auto w-18 opacity-40"><%= svg_tag "icons/station" %></div>
    <!-- 設定中の観測地点情報 -->
    <div class="mr-auto">
      <div class="text-left indent-3"><%= t('.current_station') %></div>
      <div class="font-semibold text-[#810002] text-left text-xl indent-15"><%= @station_info.prefecture %>・<%= @station_info.station_name %></div>
    </div>
    <div>
      <!-- 変更ボタン -->
      <%= button_to "#{t('shared.change')}", select_station_user_status_path, method: :get, class:"btn-primary min-w-max" %>
    </div>
  </div>
</div>

<!-- ログインユーザーの観測地点の気温を表示する -->
<div class="max-w-md px-4 mx-auto border rounded-md shadow-lg border-gray-500/20 backdrop-blur-lg mb-4">

  <div class="flex items-center justify-between py-6">
    <!-- 温度計のマーク -->
    <div class="h-auto w-18 opacity-40"><%= svg_tag "icons/temperature" %></div>
    <!-- 設定中の観測地点情報 -->
    <div class="mr-auto">
      <div class="text-left indent-5">
        <p><%= "#{format_observation_hour(@latest_record)} #{t('.latest_record_time')}" %></p>
        <p class="font-semibold text-left text-2xl indent-15"><%= "#{@latest_record&.temp.presence || t('.no_data')} ℃"%></p>
      </div>
    </div>
    <div class="mr-15">
      <p class="text-sm"><%= t('.temp_within_24_hours') %></p>
      <p><%= t('.max') %> <span class="font-semibold text-[#810002] text-2xl"><%= @max_temp || t('.no_data') %> ℃</span></p>
      <p><%= t('.min') %> <span class="font-semibold text-2xl"><%= @min_temp || t('.no_data') %> ℃</span></p>
    </div>
  </div>
</div>

<div class="max-w-md px-4 mx-auto border rounded-md shadow-lg border-gray-500/20 backdrop-blur-lg mb-4">
  <div class="mx-10">
    <!-- 現在の積雪深 -->
    <div class="my-4"><%= t('.current_snow_depth') %><span class="font-semibold text-[#810002] text-2xl"><%= " #{@latest_record&.snow.presence || t('.no_data')} cm" %></span></div>
    <!-- 前回雪かきからの増減 -->
    <div class="my-4"><%= format_snow_depth_since_last_work(current_user, current_user.user_status.station_number) %></div>
    <!-- 作用時間予測 -->
    <div class="my-4"><%= t('.work_time') %> <span class="font-semibold text-[#810002]">今後のアップデートで実装予定</span></div>
  <!-- action_statusによって雪かきスタート/ストップを切り替え -->
  <% if current_user.user_status.inactive? %>
    <%= button_to t('.start'), user_records_path, method: :post, class:"btn-secondary text-3xl my-10" %>
  <% else %>
    <p class="text-center pt-5">雪かき中…</p>
    <%= button_to t('.stop'), finish_user_records_path, method: :patch, class:"btn-secondary text-3xl my-10" %>
  <% end %>
  </div>
</div>